# -*- coding: utf-8 -*-
"""
Created on Thu Mar  7 19:53:31 2019

@author: Aputer

Rosalind Project problem ID: SUBS
"""
def motif(s,t):
    index_list=[]
    for x in range(len(s)):
        if(s[x:x+len(t)]==t):
            index_list.append(x+1)
    return(index_list)

print(motif("TGGTAAATCGACCCCAAATCGAGCAAATCGACCCAAATCGACAAATCGAAAATCGATCAGCAAATCGATGAAATCGAAAATCGACAAATCGACCAAATCGAACCAAATCGAGAAATCGACCCAAATCGAAAATCGAGAAATCGAAAATCGAACAAATCGAATTAAATCGAAAATCGACTAAAATCGAAAATCGATAAATCGAAAATCGAAAATCGAAAATCGAAAATCGAAAATCGAAAATCGAAAATCGAAAATCGACGAAATCGAAAATCGATGATCCAAATCGACATGAAATCGAAAATCGAGAAATCGAAAATCGAACAAATCGATAACGGAGAAATCGAAAATCGAGATGCGAAATCGAGGTGGTGCTAAATCGACCTGTAAATCGATCTCTCAAATCGAAAATCGAAAATCGATAAATCGAGAAATCGAGAAATCGATCTTCGAGTATTACGAAAGGTAAATCGAAAAATCGAAGAAAATCGAGAAATCGACAAATCGAGAAATCGAGGAAATCGAGAAATCGAATACAAATCGATGCTCGTGGCTCTGAACCTAGAAATCGACACAAATCGAAAGTAGGAAATCGAGAGAAATCGATTAAAATCGAACAGAAATCGACAGCAAAATCGACCTGCCAAATCGAAAATCGATTTACCCAAATCGAAAATCGACCGAACTAAATCGATAGAAATCGAAAATCGAGGAAATCGACAAATCGAATTGGTGCAAATCGAAAATCGAAAATCGAACACAAATCGAAAATCGAAAATCGATGGTAAATCGATGAAATCGATAAATCGAAAATCGACGAAATCGAGAAATCGACGATTGTAAATCGAACGCAAATCGAGTCAAATCGACCCAAATCGACACATCTGCCAAAATCGAAAATCGAAAATCGAGCGAGCAAAATCGAAAATCGAGGTGCCAAATCGAAAATCGAGGACTA","AAATCGAAA"))
        
